kind: Service
apiVersion: v1
metadata:
  name: hello-page-service
spec:
  selector:
    app: HelloPageService
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-page-deployment
  labels:
    app: HelloPageDeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: HelloPageService
  template:
    metadata:
      labels:
        app: HelloPageService
    spec:
      containers:
      - name: hello-page-service
        image: 'hello-page-service'
        imagePullPolicy: Never # allows using the local registry
        envFrom:
        - configMapRef:
            name: hello-page-config
        ports:
        - containerPort: 7000
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-page-config
data:
  HELLO_SERVICE_URL: 'http://hello-service'
  PAGES_SERVICE_URL: 'http://page-service'
